import streamlit as st

st.title('MARVEL')
st.write('  ')
st.write('  ')
st.image('marvel.jpg')

st.title('AVENGERS')
st.image('avengers.jpg')
st.write('avengers soundtrack !')
st.audio('The Avengers Theme Song.mp3')
st.title('AVENGERS CARTOON')
st.image('avengers_cartoon.jpg')
st.title('AVENGERS ENDGAME')
st.image('avengers_endgame.jpg')
st.audio('avengers_assemble.mp3')
st.title('TONY snap !!')
st.image('tony.jpg')
st.audio('i_am_iron_man.mp3')

st.write('-------------------------------------------------------------------')

st.title('GUARDIANS OF THE GALAXY')
st.image('guardians_of_galaxy.jpg')
st.write('GUARDIANS OF THE GALAXY 1 soundtrack !')
st.audio('gotg.mp3')
st.image('guardians_of_galaxy_2.jpg')
st.write('GUARDIANS OF THE GALAXY 2 soundtrack !')
st.audio('gotg2.mp3')
st.image('gotg_cartoon.jpg')
st.write('We are the Guardians of the galaxy !!')
st.audio('guardian_of_galaxy.mp3')
st.write('Dance off Bro !!')
st.audio('dance_off.mp3')
st.image('baby_groot.jpg')
st.audio('baby groot.mp3')

st.write('-------------------------------------------------------------------')
st.title('THE MARVEL BUNCH')
st.audio('marvel bunch.mp3')
st.audio('the_marvel_bunch.mp3')
st.video('https://www.youtube.com/watch?v=-onk-Qm7ATw')

st.write('-------------------------------------------------------------------')

st.title('And we are waiting for ....')
st.write('  ')
st.video('https://www.youtube.com/watch?v=rt-2cxAiPJk')